# Site settings

title: Tiernan J. Cahill, Media Researcher
author: Tiernan J. Cahill
# email: 
description: ""
domain: tj-cahill.github.io
url: https://tj-cahill.github.io 
# baseurl: 

# twitter_username: 
# github_username: 

# Build settings
theme: minima
plugins:
  - jekyll-feed

twitter_username: tj_kritik
linkedin_username: tjcahill
github_username: tj-cahill

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
